import Link from "next/link";

const priorities = [
  ["01", "Define the case", "Agree on the service model, country or programme, population, and the decision the case study should inform."],
  ["02", "Build the evidence base", "Collect programme evidence, peer-reviewed research, policy documents, implementation data, and member perspectives."],
  ["03", "Compare what works", "Assess access, integration, community participation, financing, implementation constraints, and transferability."],
  ["04", "Translate the findings", "Develop a case-study report with practical lessons and recommendations for policy and implementation."],
];

const evidence = [
  ["Country and programme cases", "Existing integrated HIV service models, implementation experience, and results."],
  ["Research and policy sources", "Peer-reviewed studies, guidance, evaluations, policy documents, and datasets."],
  ["Committee perspectives", "Member observations, proposed questions, concerns, and recommendations."],
];

const decisions = [
  ["Confirmed", "Primary output", "Integrated HIV service delivery case study report"],
  ["To decide", "Case definition", "Final policy question, population, setting, and intended users"],
  ["In collection", "Evidence base", "Country and programme cases, member experience, and documented sources"],
  ["To assign", "Governance", "Contributors, co-authors, reviewers, owners, and next checkpoint"],
];

const criteria = [
  ["Access & equity", "Who reaches the service, who does not, and which barriers remain?"],
  ["Service integration", "How are HIV, HPV, cervical-cancer, and SRHR pathways connected?"],
  ["Community leadership", "How are communities involved in design, delivery, and accountability?"],
  ["Implementation", "What workforce, referral, data, and coordination conditions are required?"],
  ["Financing", "How is the model funded and what affects its sustainability?"],
  ["Transferability", "Which elements can be adapted to other settings, and under what conditions?"],
];

export default function Home() {
  return <main className="min-h-screen bg-[#f7f7f5] text-[#101010]">
    <nav className="sticky top-0 z-20 border-b-2 border-[#202020] bg-[#f7f7f5]/95 backdrop-blur"><div className="mx-auto flex min-h-[72px] max-w-[1240px] items-center justify-between gap-5 px-5 sm:px-8"><a href="#top" className="text-sm font-black tracking-[.02em]">HIV/AIDS &amp; STIs COMMITTEE</a><div className="flex items-center gap-5 text-sm font-bold"><a href="#direction" className="hidden md:block hover:text-[#9f1420]">Strategic direction</a><a href="#workplan" className="hidden sm:block hover:text-[#9f1420]">Workplan</a><a href="#evidence" className="hidden lg:block hover:text-[#9f1420]">Evidence needed</a><Link href="/workspace" className="bg-[#b81725] px-4 py-3 text-white hover:bg-[#8f101b]">Open Committee Lab</Link></div></div></nav>

    <header id="top" className="border-b-2 border-[#202020]"><div className="mx-auto grid max-w-[1240px] lg:grid-cols-[1.35fr_.65fr]"><div className="px-5 py-16 sm:px-8 sm:py-24 lg:border-r-2 lg:border-[#202020]"><div className="mb-7 flex flex-wrap items-center gap-3"><p className="text-sm font-black uppercase tracking-[.16em] text-[#99131f]">Committee working hub</p><span className="border border-[#23613d] bg-[#dcecdf] px-2.5 py-1 text-sm font-black text-[#16482c]">● Active member workspace</span></div><h1 className="max-w-4xl text-[clamp(3.2rem,7.5vw,7rem)] font-black leading-[.91] tracking-[-.065em]">Integrated HIV services<br/><span className="text-[#b81725]">case study.</span></h1><p className="mt-9 max-w-3xl text-xl font-semibold leading-8 text-[#252525]">A shared space for the HIV/AIDS &amp; STIs Committee to define the case-study scope, assemble evidence, and develop practical recommendations.</p><Link href="/workspace" className="mt-9 inline-flex bg-[#111111] px-6 py-4 text-base font-black text-white hover:bg-[#b81725]">Contribute to the case study <span className="ml-4">→</span></Link></div><aside className="grid bg-[#ededE9] sm:grid-cols-3 lg:grid-cols-1"><div className="border-b border-[#7b7b75] p-6 sm:border-b-0 sm:border-r lg:border-b lg:border-r-0"><p className="text-sm font-black uppercase tracking-[.1em] text-[#4a4a46]">Status</p><p className="mt-2 text-xl font-black">Scoping and evidence collection</p></div><div className="border-b border-[#7b7b75] p-6 sm:border-b-0 sm:border-r lg:border-b lg:border-r-0"><p className="text-sm font-black uppercase tracking-[.1em] text-[#4a4a46]">Working question</p><p className="mt-2 text-lg font-bold leading-7">What makes integrated HIV-related services practical, equitable, and scalable?</p></div><div className="p-6"><p className="text-sm font-black uppercase tracking-[.1em] text-[#4a4a46]">Current focus</p><p className="mt-2 text-lg font-bold leading-7">Service integration, community-led models, policy, financing, and monitoring.</p></div></aside></div></header>

    <figure className="relative border-b-2 border-[#202020] bg-[#ecece8]"><img src="/integrated-care-pathways.png" alt="Illustration of community members, health workers, testing, vaccination, reproductive health, and referral pathways connected through an integrated care network" className="h-[clamp(300px,24vw,640px)] w-full object-cover object-center"/><figcaption className="absolute bottom-0 right-0 max-w-md border-l-2 border-t-2 border-[#202020] bg-[#f7f7f5] px-5 py-3 text-sm font-bold text-[#292929]">Integrated services connect community leadership, prevention, testing, referral, treatment, and follow-up.</figcaption></figure>

    <section id="direction" className="border-b-2 border-[#202020] bg-[#111111] py-20 text-white sm:py-24"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><p className="text-sm font-black uppercase tracking-[.14em] text-[#ff6975]">Strategic direction from the Co-Chair Meeting</p><h2 className="mt-5 text-4xl font-black leading-[1.02] tracking-[-.05em] sm:text-5xl">One focused case study, built for practical use.</h2><p className="mt-6 text-base font-semibold leading-7 text-[#f0f0ec]">The Co-Chairs agreed to prioritise an integrated HIV service delivery case study report as the Committee’s first substantive output. A webinar will support the work only after the core message and audience are clear.</p></div><div className="grid border-2 border-[#777771] md:grid-cols-2"><article className="border-b border-[#777771] p-6 md:border-r"><p className="text-sm font-black text-[#ff6975]">PROPOSED SCOPE</p><p className="mt-3 font-semibold leading-7">Explore links between HIV services, HPV vaccination, cervical-cancer screening, and sexual and reproductive health, including referral pathways, community-led systems, and co-design.</p></article><article className="border-b border-[#777771] p-6"><p className="text-sm font-black text-[#ff6975]">COMMITTEE DECISIONS</p><p className="mt-3 font-semibold leading-7">Confirm the policy question, population and setting, intended users, country or programme examples, evidence needs, contributors, co-authors, and reviewers.</p></article><article className="border-b border-[#777771] p-6 md:border-b-0 md:border-r"><p className="text-sm font-black text-[#ff6975]">EVIDENCE APPROACH</p><p className="mt-3 font-semibold leading-7">Use cleared or de-identified evidence, member experience, and documented programme practice. A new dataset is not required for the initial scoping decision.</p></article><article className="p-6"><p className="text-sm font-black text-[#ff6975]">COLLABORATION</p><p className="mt-3 font-semibold leading-7">Clarify scope, timing, responsibilities, and contribution levels with the Gender Committee and other partners, while mapping member networks for evidence and dissemination.</p></article></div></div><div className="mt-8 border-l-4 border-[#ff6975] bg-[#202020] p-6"><p className="text-sm font-black uppercase tracking-[.12em] text-[#ff8791]">Immediate objective</p><p className="mt-2 text-xl font-black leading-8">Leave the next committee discussion with one workable direction, named owners, and a clear checkpoint for the revised ToR, draft Position Paper, and case-study development.</p></div></div></section>

    <section id="workplan" className="border-b-2 border-[#202020] bg-white py-20 sm:py-24"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><div className="grid gap-6 md:grid-cols-[280px_1fr]"><div><p className="text-sm font-black uppercase tracking-[.14em] text-[#99131f]">Case-study workplan</p><h2 className="mt-4 text-4xl font-black leading-[1.02] tracking-[-.05em]">How the committee will move from ideas to a report.</h2></div><div className="border-t-2 border-[#202020]">{priorities.map(([number,title,detail])=><article key={number} className="grid gap-3 border-b border-[#797973] py-7 sm:grid-cols-[72px_220px_1fr] sm:gap-6"><p className="text-2xl font-black text-[#b81725]">{number}</p><h3 className="text-xl font-black">{title}</h3><p className="text-base font-medium leading-7 text-[#292929]">{detail}</p></article>)}</div></div></div></section>

    <section className="border-b-2 border-[#202020] bg-[#ecece8] py-20 sm:py-24"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><div className="grid gap-12 lg:grid-cols-2"><div><p className="text-sm font-black uppercase tracking-[.14em] text-[#99131f]">Decision tracker</p><h2 className="mt-4 text-4xl font-black tracking-[-.05em]">What is settled—and what still needs a decision.</h2><div className="mt-8 border-t-2 border-[#202020]">{decisions.map(([status,label,detail])=><article key={label} className="grid gap-2 border-b border-[#777771] py-5 sm:grid-cols-[110px_150px_1fr]"><span className={`h-fit w-fit px-2 py-1 text-sm font-black ${status==="Confirmed"?"bg-[#16482c] text-white":status==="In collection"?"bg-[#9f6c00] text-white":"border border-[#555550] bg-white text-[#202020]"}`}>{status}</span><h3 className="font-black">{label}</h3><p className="font-medium leading-6 text-[#292929]">{detail}</p></article>)}</div></div><div><p className="text-sm font-black uppercase tracking-[.14em] text-[#99131f]">Output progress</p><h2 className="mt-4 text-4xl font-black tracking-[-.05em]">A visible path to publication.</h2><ol className="mt-8 border-2 border-[#202020] bg-white"><li className="flex gap-5 border-b border-[#777771] p-5"><span className="font-black text-[#99131f]">01</span><div><p className="font-black">Scope</p><p className="mt-1 font-medium text-[#292929]">Active — policy question, population, setting, and users</p></div></li><li className="flex gap-5 border-b border-[#777771] p-5"><span className="font-black">02</span><div><p className="font-black">Evidence</p><p className="mt-1 font-medium text-[#292929]">Active — cases, sources, and member perspectives</p></div></li>{[["03","Analysis","Pending scope confirmation"],["04","Draft and review","Pending analysis"],["05","Publication and webinar","Pending approved message and audience"]].map(([n,t,s])=><li key={n} className="flex gap-5 border-b border-[#777771] p-5 last:border-b-0"><span className="font-black text-[#555550]">{n}</span><div><p className="font-black">{t}</p><p className="mt-1 font-medium text-[#454541]">{s}</p></div></li>)}</ol></div></div></div></section>

    <section className="border-b-2 border-[#202020] bg-white py-20 sm:py-24"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><div className="mb-10 max-w-3xl"><p className="text-sm font-black uppercase tracking-[.14em] text-[#99131f]">Case evaluation framework</p><h2 className="mt-4 text-4xl font-black tracking-[-.05em] sm:text-5xl">A consistent test for every proposed case.</h2><p className="mt-5 text-lg font-semibold leading-8 text-[#292929]">Members can use these six lenses when submitting or reviewing a country or programme example.</p></div><div className="grid border-2 border-[#202020] md:grid-cols-2 lg:grid-cols-3">{criteria.map(([title,detail],index)=><article key={title} className={`p-6 ${index<3?"border-b border-[#777771] lg:border-b":index<4?"border-b border-[#777771] md:border-b-0":""} ${index%3!==2?"lg:border-r":""} ${index%2===0?"md:border-r lg:border-r":"md:border-r-0"}`}><p className="text-sm font-black text-[#99131f]">0{index+1}</p><h3 className="mt-3 text-xl font-black">{title}</h3><p className="mt-3 font-medium leading-7 text-[#292929]">{detail}</p></article>)}</div></div></section>

    <section id="evidence" className="border-b-2 border-[#202020] bg-[#ecece8] py-20 sm:py-24"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><div className="mb-10 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-black uppercase tracking-[.14em] text-[#99131f]">Evidence needed</p><h2 className="mt-4 max-w-3xl text-4xl font-black leading-[1.03] tracking-[-.05em] sm:text-5xl">What committee members can contribute now.</h2></div><Link href="/workspace" className="font-black text-[#9f1420] underline decoration-2 underline-offset-4">Add a contribution →</Link></div><div className="grid border-2 border-[#202020] md:grid-cols-3">{evidence.map(([title,detail],index)=><article key={title} className={`bg-white p-7 ${index<2?"border-b-2 border-[#202020] md:border-b-0 md:border-r-2":""}`}><p className="text-sm font-black text-[#99131f]">0{index+1}</p><h3 className="mt-5 text-2xl font-black tracking-[-.025em]">{title}</h3><p className="mt-4 font-medium leading-7 text-[#292929]">{detail}</p></article>)}</div></div></section>

    <section className="bg-[#111111] py-16 text-white"><div className="mx-auto flex max-w-[1240px] flex-col gap-7 px-5 sm:px-8 md:flex-row md:items-center md:justify-between"><div><p className="text-sm font-black uppercase tracking-[.14em] text-[#ff6975]">Member workspace</p><h2 className="mt-3 max-w-3xl text-3xl font-black tracking-[-.035em] sm:text-4xl">Share a case, source, or perspective with the committee.</h2></div><Link href="/workspace" className="shrink-0 bg-[#d12736] px-6 py-4 font-black text-white hover:bg-[#ee3a49]">Enter Committee Lab →</Link></div></section>
    <footer className="border-t border-[#484848] bg-[#111111] py-6 text-white"><div className="mx-auto flex max-w-[1240px] flex-col gap-2 px-5 text-sm font-semibold text-[#deded9] sm:flex-row sm:justify-between sm:px-8"><p>HIV/AIDS &amp; STIs Committee · Integrated Services Case Study Lab</p><p>Concept &amp; coordination: Hyunji Kim</p></div></footer>
  </main>;
}
