"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Item={id:number;type:"opinion"|"resource"|"case";title:string;summary:string;url?:string|null;geography:string;theme:string;status:string;authorName:string;createdAt:string;votes:number;voted:boolean};
const themes=["Integrated service pathways","Community-led models","Policy & financing","Monitoring frameworks"];

export default function Workspace({memberName}:{memberName:string}){
 const [items,setItems]=useState<Item[]>([]),[filter,setFilter]=useState("all"),[open,setOpen]=useState(false),[loading,setLoading]=useState(true);
 const load=()=>fetch("/api/contributions").then(r=>r.json()).then(d=>{setItems(d.items??[]);setLoading(false)});
 useEffect(()=>{load()},[]);
 const shown=useMemo(()=>filter==="all"?items:items.filter(i=>i.type===filter),[items,filter]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch("/api/contributions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});if(r.ok){e.currentTarget.reset();setOpen(false);load()}}
 async function vote(id:number){await fetch(`/api/contributions/${id}/vote`,{method:"POST"});load()}
 const counts={resources:items.filter(i=>i.type==="resource").length,cases:items.filter(i=>i.type==="case").length,opinions:items.filter(i=>i.type==="opinion").length};

 return <main className="min-h-screen bg-[#ecece8] text-[#101010]">
  <header className="border-b-2 border-[#202020] bg-[#111111] text-white"><div className="mx-auto flex max-w-[1320px] items-center justify-between gap-5 px-5 py-5"><div><p className="text-sm font-black tracking-[.13em] text-[#ff6975]">HIV/AIDS &amp; STIs COMMITTEE</p><h1 className="mt-1 text-xl font-black">Integrated Services Case Study Lab</h1></div><div className="text-right text-sm font-semibold"><p>{memberName}</p><p className="text-[#deded9]">Open access</p></div></div></header>

  <div className="mx-auto max-w-[1320px] px-5 py-8"><section className="grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><div className="border-2 border-[#202020] bg-white p-7"><span className="text-sm font-black text-[#99131f]">WORKING QUESTION</span><h2 className="mt-3 text-3xl font-black tracking-[-.04em]">What makes integrated HIV-related services practical, equitable, and scalable?</h2><p className="mt-4 max-w-3xl text-base font-medium leading-7 text-[#292929]">Contribute evidence on HIV services connected with HPV vaccination, cervical-cancer screening, sexual and reproductive health, community co-design, and enabling policy or financing.</p></div><div className="grid grid-cols-3 border-2 border-[#202020] bg-[#111111] text-white">{[[counts.resources,"Resources"],[counts.cases,"Cases"],[counts.opinions,"Opinions"]].map(x=><div className="flex flex-col justify-center border-r border-[#666666] p-4 last:border-r-0" key={x[1]}><b className="text-3xl text-[#ff6975]">{x[0]}</b><span className="mt-1 text-sm font-bold text-white">{x[1]}</span></div>)}</div></section>

  <section className="mt-7 grid gap-7 lg:grid-cols-[240px_1fr]"><aside><button onClick={()=>setOpen(!open)} className="w-full bg-[#b81725] px-4 py-3.5 font-black text-white hover:bg-[#8f101b]">+ Add contribution</button><p className="mt-7 text-sm font-black text-[#3d3d39]">FILTER VIEW</p><div className="mt-2 space-y-1">{[["all","All contributions"],["case","Country / programme cases"],["resource","Evidence & resources"],["opinion","Member perspectives"]].map(x=><button key={x[0]} onClick={()=>setFilter(x[0])} className={`w-full px-3 py-2.5 text-left text-sm font-bold ${filter===x[0]?"bg-[#111111] text-white":"text-[#202020] hover:bg-white"}`}>{x[1]}</button>)}</div><div className="mt-8 border-t-2 border-[#777771] pt-5"><p className="text-sm font-black">SCOPING LENSES</p>{themes.map(t=><p key={t} className="mt-3 text-sm font-semibold text-[#343430]">{t}</p>)}</div></aside>

  <div>{open&&<form onSubmit={submit} className="mb-5 grid gap-3 border-2 border-[#202020] bg-white p-6 sm:grid-cols-2"><h3 className="text-xl font-black sm:col-span-2">Add to the evidence base</h3><label className="text-sm font-bold">Contribution type<select name="type" required className="mt-1 w-full border-2 border-[#666660] bg-white p-3 text-base"><option value="case">Country / programme case</option><option value="resource">Evidence / resource</option><option value="opinion">Member perspective</option></select></label><label className="text-sm font-bold">Theme<select name="theme" required className="mt-1 w-full border-2 border-[#666660] bg-white p-3 text-base">{themes.map(t=><option key={t}>{t}</option>)}</select></label><input name="title" aria-label="Contribution title" required className="border-2 border-[#666660] p-3 text-base sm:col-span-2" placeholder="Clear title"/><textarea name="summary" aria-label="Contribution summary" required className="min-h-28 border-2 border-[#666660] p-3 text-base sm:col-span-2" placeholder="What does this contribute to the case-study decision?"/><input name="geography" aria-label="Country or region" className="border-2 border-[#666660] p-3 text-base" placeholder="Country / region (or Global)"/><input name="url" aria-label="Source URL" type="url" className="border-2 border-[#666660] p-3 text-base" placeholder="Source URL (optional)"/><button className="bg-[#111111] px-4 py-3.5 font-black text-white hover:bg-[#b81725] sm:col-span-2">Submit contribution</button></form>}

  <div className="mb-3 flex items-center justify-between"><h3 className="text-xl font-black">Evidence board</h3><span className="text-sm font-bold text-[#3d3d39]">{shown.length} items</span></div>{loading?<div className="border-2 border-[#777771] bg-white p-8 font-semibold text-[#30302c]">Loading evidence…</div>:shown.length===0?<div className="border-2 border-dashed border-[#777771] bg-white p-10 text-center"><b>No contributions in this view yet.</b><p className="mt-2 font-medium text-[#30302c]">Add the first case, resource, or perspective.</p></div>:<div className="space-y-3">{shown.map(i=><article key={i.id} className="grid gap-4 border-2 border-[#777771] bg-white p-6 sm:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap gap-2 text-sm font-bold"><span className="bg-[#f1d7da] px-2 py-1 text-[#7f101a]">{i.type}</span><span className="bg-[#deded9] px-2 py-1 text-[#202020]">{i.theme}</span><span className="bg-[#deded9] px-2 py-1 text-[#202020]">{i.geography}</span></div><h4 className="mt-3 text-xl font-black">{i.title}</h4><p className="mt-2 font-medium leading-7 text-[#292929]">{i.summary}</p>{i.url&&<a className="mt-3 inline-block text-sm font-black text-[#8f101b] underline decoration-2 underline-offset-4" target="_blank" rel="noreferrer" href={i.url}>Open source ↗</a>}<p className="mt-4 text-sm font-semibold text-[#454541]">Added by {i.authorName}</p></div><button onClick={()=>vote(i.id)} className={`h-fit min-w-20 border-2 px-3 py-2 text-sm font-black ${i.voted?"border-[#99131f] text-[#8f101b]":"border-[#555550] text-[#202020]"}`}>▲ {i.votes}</button></article>)}</div>}</div></section></div>
 </main>;
}
